<a href="https://colab.research.google.com/github/Amyerm/ClassFiles/blob/main/S06_Actividad_02_ALGEBRALINEAL_MATRICULA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---


**Nombre completo: Ari Daniel Mendoza Enrriquez  
**Matrícula: 271756

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [1]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [2]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [3]:
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print("Norma del producto A:", norma_A)
print("Norma del producto B:", norma_B)
print("Norma del producto C:", norma_C)

Norma del producto A: 7.449161026585477
Norma del producto B: 6.777167549942971
Norma del producto C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [4]:
producto_punto_AB = np.dot(producto_A, producto_B)
producto_punto_AC = np.dot(producto_A, producto_C)

print("Producto punto entre A y B:", producto_punto_AB)
print("Producto punto entre A y C:", producto_punto_AC)

coseno_AB = producto_punto_AB / (norma_A * norma_B)
coseno_AC = producto_punto_AC / (norma_A * norma_C)
angulo_AB = np.degrees(np.arccos(coseno_AB))
angulo_AC = np.degrees(np.arccos(coseno_AC))

print("\nÁngulo entre A y B:", angulo_AB, "grados")
print("Ángulo entre A y C:", angulo_AC, "grados")
# El producto B es similar al producto A porque el ángulo entre
# sus vectores es menor. Un ángulo menor indica que ambos vectores
# son más parecidos en sus características.


Producto punto entre A y B: 50.46
Producto punto entre A y C: 26.5

Ángulo entre A y B: 1.7745815839558179 grados
Ángulo entre A y C: 47.22509268261831 grados


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [5]:
producto_A_normalizado = producto_A / norma_A
producto_B_normalizado = producto_B / norma_B
producto_C_normalizado = producto_C / norma_C

print("Producto A normalizado:")
print(producto_A_normalizado)

print("\nProducto B normalizado:")
print(producto_B_normalizado)

print("\nProducto C normalizado:")
print(producto_C_normalizado)

print("\nNorma de A normalizado:", np.linalg.norm(producto_A_normalizado))
print("Norma de B normalizado:", np.linalg.norm(producto_B_normalizado))
print("Norma de C normalizado:", np.linalg.norm(producto_C_normalizado))

Producto A normalizado:
[0.60409488 0.42957858 0.67121653]

Producto B normalizado:
[0.59021707 0.41315195 0.69350506]

Producto C normalizado:
[0.19090089 0.95450444 0.22908106]

Norma de A normalizado: 1.0
Norma de B normalizado: 1.0
Norma de C normalizado: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [6]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [7]:
multiplicacion_elementos = M * P
multiplicacion_MP = M @ P
multiplicacion_PM = P @ M

print("Multiplicación elemento a elemento M * P:")
print(multiplicacion_elementos)

print("\nMultiplicación matricial M @ P:")
print(multiplicacion_MP)

print("\nMultiplicación matricial P @ M:")
print(multiplicacion_PM)

# M * P multiplica los elementos ubicados en la misma posición,
# mientras que M @ P combina las filas de M con las columnas de P.
# Las matrices son compatibles porque ambas tienen forma (2, 2).
# P @ M no da el mismo resultado que M @ P porque el orden de la
# multiplicación matricial modifica el resultado.

Multiplicación elemento a elemento M * P:
[[3. 0.]
 [0. 6.]]

Multiplicación matricial M @ P:
[[3.  2. ]
 [1.5 6. ]]

Multiplicación matricial P @ M:
[[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [8]:
determinante_M = np.linalg.det(M)
print("Determinante de M:", determinante_M)
print("¿M tiene inversa?", determinante_M != 0)

M_inv = np.linalg.inv(M)

print("\nInversa de M:")
print(M_inv)

verificacion = M @ M_inv

print("\nVerificación M @ M_inv:")
print(verificacion)


Determinante de M: 5.000000000000001
¿M tiene inversa? True

Inversa de M:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Verificación M @ M_inv:
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [9]:
b = np.array([180, 300])

x = np.linalg.solve(M, b)

print("Unidades necesarias de cada insumo:")
print(x)

verificacion_sistema = M @ x

print("\nVerificación M @ x:")
print(verificacion_sistema)

print("\nValores esperados de b:")
print(b)

Unidades necesarias de cada insumo:
[48. 84.]

Verificación M @ x:
[180. 300.]

Valores esperados de b:
[180 300]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [10]:
distancia_AB = np.linalg.norm(producto_A - producto_B)
distancia_AC = np.linalg.norm(producto_A - producto_C)

print("Distancia entre A y B:", distancia_AB)
print("Distancia entre A y C:", distancia_AC)

similitud_AB = np.dot(producto_A, producto_B) / (
    np.linalg.norm(producto_A) * np.linalg.norm(producto_B)
)

similitud_AC = np.dot(producto_A, producto_C) / (
    np.linalg.norm(producto_A) * np.linalg.norm(producto_C)
)

print("\nSimilitud coseno entre A y B:", similitud_AB)
print("Similitud coseno entre A y C:", similitud_AC)

conclusion = (
    "El producto B es más parecido al producto A. "
    "Tiene una distancia euclidiana menor y una similitud coseno más cercana a 1, "
    "por lo que ambas métricas coinciden en la misma conclusión."
)

print("\nConclusión:")
print(conclusion)

Distancia entre A y B: 0.7071067811865476
Distancia entre A y C: 5.470831746635972

Similitud coseno entre A y B: 0.9995203969214979
Similitud coseno entre A y C: 0.6791199021706347

Conclusión:
El producto B es más parecido al producto A. Tiene una distancia euclidiana menor y una similitud coseno más cercana a 1, por lo que ambas métricas coinciden en la misma conclusión.


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.